version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cukz
    overwrite: yes

permissions:
  - object: /home/ubuntu/cukz
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/run_docker.sh
      timeout: 120
      runas: root