spring:
  config:
    activate:
      on-profile: default

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/cukz
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#jwt:
#  secret_key: ${JWT_SECRET_KEY}