spring:
  config:
    activate:
      on-profile: default

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: ENC(L6u0PIDNX8L/AfPWlUWfl5yNpwNrT19ASEaUgdB/vlFcPntBO6lMNm4tk+S2jL3VJnb3MrOxq3JomczQugoOWYMtocsrtwROICC0sLeJH7YEZXEqnphr0jJ32BQFdDhl+ZOLXSFYaaXMfJGpw4bdNZHeti9rpbur)
    username: ENC(NrBotP5u+u/gw9PYSBZ4SZ2JEoqGqwGN)
    password: ENC(6QBAQWBB9UhtlwFSObzzwzFCCHjPC0C66MjuUvRLXV8=)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: cukz.official@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

cloud:
  aws:
    s3:
      bucket: ENC(XMrY8EvccgS1ME2kyQyaeA2fEV6nF7ava9iBsYwOyog=)
    stack.auto: false
    region:
      static: ENC(YFUlb95nE4ncc/vp2ut/9pjki2bO5hYC83MBm3uWgS0=)
    credentials:
      accessKey: ENC(nKGPfLtXJVpkRDlNi73McWhJd3PIKdDTfA853KSGcwAP3imslJvpKw==)
      secretKey: ENC(QzjrxI9NhXLk3N1qZ+dmftGJpu4WOs5z/yLBP3Kk/VdpRN5dCy6po0VRD9EA2FRdy9Ieb9+2rphZCLY7N6OhgQ==)

jasypt:
  encryptor:
    private-key-string: ${JASYPT_KEY}
    algorithm: ${JASYPT_ALGORITHM}