# Test profile
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: cukz.official@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

cloud:
  aws:
    s3:
      bucket: ENC(XMrY8EvccgS1ME2kyQyaeA2fEV6nF7ava9iBsYwOyog=)
    stack.auto: false
    region:
      static: ENC(YFUlb95nE4ncc/vp2ut/9pjki2bO5hYC83MBm3uWgS0=)
    credentials:
      accessKey: ENC(nKGPfLtXJVpkRDlNi73McWhJd3PIKdDTfA853KSGcwAP3imslJvpKw==)
      secretKey: ENC(QzjrxI9NhXLk3N1qZ+dmftGJpu4WOs5z/yLBP3Kk/VdpRN5dCy6po0VRD9EA2FRdy9Ieb9+2rphZCLY7N6OhgQ==)

jasypt:
  encryptor:
    private-key-string: ${JASYPT_KEY}
    algorithm: ${JASYPT_ALGORITHM}